### ISSUE TITLE
Upgrade Ready Set team photos and job titles.

### ISSUE THREAD

**Issue by fersanz-87** [Ealanisln/ready-set#12]
Current Ready Set team photos are not in good shape, some of them do not have white background and need to be updated. Also job titles have to be updated with the most recent info.

**Comment by fersanz-87** [comment]
Update in progress now, because we need to edit some pics and add new members to Ready Set Team.

**Comment by fersanz-87** [comment]
Photos and job titles added, including new team members on Ready Set. Also I added new profiles, new skills and a short description about each profile.

**Comment by Ealanisln** [comment]
This photo is not being showed, could you please fix it? @fersanz-87

Thanks in advance!  

<img width="345" alt="Screenshot 2024-10-07 at 12 05 19 p m" src="https://github.com/user-attachments/assets/bbacbf84-5428-47e4-bd2d-2726cd844729">
<img width="539" alt="Screenshot 2024-10-07 at 12 05 15 p m" src="https://github.com/user-attachments/assets/7b41af31-e2cb-4953-886c-138fafc932f3">

**Comment by Ealanisln** [comment]
Issue was fixed.
